### ISSUE TITLE
Unreadable /wp current

### ISSUE THREAD

**Issue by cakoshakib** [markdstouffer/ani-bot#20]
This simply makes no sense, please fix. Thanks.

![](https://i.imgur.com/sZffIyw.png)

**Comment by markdstouffer** [comment]
Please use the proper format for future issues, and cut back on the sass, but I will start working on this. Thanks.

**Comment by cakoshakib** [comment]
Where is the issue template?

**Comment by markdstouffer** [comment]
Closed with b0b40273277a3cf5569f68dace68492625080df0
